CREATE DATABASE UniversityDB;


USE UniversityDB;


CREATE TABLE INSTRUCTORS (
    InstructorID VARCHAR(15) PRIMARY KEY,
    InstructorName VARCHAR(100) NOT NULL,
    Expertise VARCHAR(50),
    Email VARCHAR(100) UNIQUE
);

CREATE TABLE COURSES (
    CourseID VARCHAR(15) PRIMARY KEY,
    CourseName VARCHAR(150) NOT NULL,
    Description TEXT
);

CREATE TABLE LEARNERS (
    LearnerID VARCHAR(15) PRIMARY KEY,
    LearnerName VARCHAR(100) NOT NULL,
    Email VARCHAR(100) UNIQUE,
    PhoneNumber VARCHAR(20)
);

CREATE TABLE COURSE_INSTRUCTOR (
    AssignmentID VARCHAR(15) PRIMARY KEY,
    Shift VARCHAR(20),
    InstructorID VARCHAR(15),
    CourseID VARCHAR(15),
    FOREIGN KEY (InstructorID) REFERENCES INSTRUCTORS(InstructorID),
    FOREIGN KEY (CourseID) REFERENCES COURSES(CourseID)
);

CREATE TABLE LECTURES (
    LectureID VARCHAR(15) PRIMARY KEY,
    Title VARCHAR(255),
    Content TEXT,
    CourseID VARCHAR(15),
    FOREIGN KEY (CourseID) REFERENCES COURSES(CourseID)
);

CREATE TABLE ENROLLMENTS (
    EnrollmentID VARCHAR(15) PRIMARY KEY,
    EnrollmentDate DATE,
    LearnerID VARCHAR(15),
    AssignmentID VARCHAR(15),
    FOREIGN KEY (LearnerID) REFERENCES LEARNERS(LearnerID),
    FOREIGN KEY (AssignmentID) REFERENCES COURSE_INSTRUCTOR(AssignmentID)
);